//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> Cell { get; set; }
        public Nullable<long> Cell2 { get; set; }
        public Nullable<int> AccountCode { get; set; }
        public Nullable<long> AccountBalance { get; set; }
        public Nullable<short> DealsInProgress { get; set; }
        public Nullable<short> DealsClosed { get; set; }
        public string Estate { get; set; }
        public string Area { get; set; }
        public string Especiality { get; set; }
    }
}
